@echo off
echo exit|nslookup - www.baidu.com.
echo exit|nslookup - test2.
echo exit|nslookup - cctv1.net.
echo exit|nslookup - test1.
echo exit|nslookup - sohu.
echo exit|nslookup - test1.
echo exit|nslookup - test1.
echo exit|nslookup - test1.
echo exit|nslookup - test0.
echo exit|nslookup - www.bilibili.tv
echo exit|nslookup - www.bilibili.tv
echo exit|nslookup - www.baidu.com.
echo exit|nslookup - www.baidu.com.
echo exit|nslookup - test2.
echo exit|nslookup - cctv1.net.
echo exit|nslookup - test1.
echo exit|nslookup - sohu.
echo exit|nslookup - test1.
echo exit|nslookup - test1.
echo exit|nslookup - test1.
echo exit|nslookup - test0.
echo exit|nslookup - www.bilibili.tv
echo exit|nslookup - www.bilibili.tv
echo exit|nslookup - www.baidu.com.
echo exit|nslookup - www.baidu.com.
echo exit|nslookup - test2.
echo exit|nslookup - cctv1.net.
echo exit|nslookup - test1.
echo exit|nslookup - sohu.
echo exit|nslookup - test1.
echo exit|nslookup - test1.
echo exit|nslookup - test1.
echo exit|nslookup - test0.
echo exit|nslookup - www.bilibili.tv
echo exit|nslookup - www.bilibili.tv
echo exit|nslookup - www.baidu.com.
nslookup - test1.
pause